In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

In [2]:
df = pd.read_csv('/content/drive/MyDrive/ObesityDataSet_raw_and_data_sinthetic (1).csv')

In [3]:
df.head()

   Gender   Age  Height  ...        CALC                 MTRANS           NObeyesdad
0  Female  21.0    1.62  ...          no  Public_Transportation        Normal_Weight
1  Female  21.0    1.52  ...   Sometimes  Public_Transportation        Normal_Weight
2    Male  23.0    1.80  ...  Frequently  Public_Transportation        Normal_Weight
3    Male  27.0    1.80  ...  Frequently                Walking   Overweight_Level_I
4    Male  22.0    1.78  ...   Sometimes  Public_Transportation  Overweight_Level_II

[5 rows x 17 columns]

In [4]:
df.tail(6)

      Gender        Age  ...                 MTRANS        NObeyesdad
2105  Female  21.285965  ...  Public_Transportation  Obesity_Type_III
2106  Female  20.976842  ...  Public_Transportation  Obesity_Type_III
2107  Female  21.982942  ...  Public_Transportation  Obesity_Type_III
2108  Female  22.524036  ...  Public_Transportation  Obesity_Type_III
2109  Female  24.361936  ...  Public_Transportation  Obesity_Type_III
2110  Female  23.664709  ...  Public_Transportation  Obesity_Type_III

[6 rows x 17 columns]

In [5]:
df.iloc[[501,518,516]]   #showing synthetic data

     Gender        Age  ...                 MTRANS           NObeyesdad
501  Female  21.853826  ...  Public_Transportation     Obesity_Type_III
518  Female  23.501249  ...  Public_Transportation  Insufficient_Weight
516  Female  21.491055  ...  Public_Transportation  Insufficient_Weight

[3 rows x 17 columns]

In [6]:
#removing Height and weight colms as they are used in the BMI calculation
df = df.drop(columns=['Height', 'Weight'])
print(df.shape)

(2111, 15)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   float64
 2   family_history_with_overweight  2111 non-null   object
 3   FAVC                            2111 non-null   object
 4   FCVC                            2111 non-null   float64
 5   NCP                             2111 non-null   float64
 6   CAEC                            2111 non-null   object
 7   SMOKE                           2111 non-null   object
 8   CH2O                            2111 non-null   float64
 9   SCC                             2111 non-null   object
 10  FAF                             2111 non-null   float64
 11  TUE                             2111 non-null   float64
 12  CALC                            2111 non-null   object
 13  MTRANS                          2111 non-null   object
 14  NObeyesdad                      2111 non-null   object
dtypes: float64(6), object(9)
memory usage: 247.5+ KB

In [8]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Gender, Age, family_history_with_overweight, FAVC, FCVC, NCP, CAEC, SMOKE, CH2O, SCC, FAF, TUE, CALC, MTRANS, NObeyesdad]
Index: []

In [9]:
#Converting object variables to category var
columns = ["Gender", "family_history_with_overweight", "FAVC", "CAEC", "SMOKE", "SCC", "CALC", "MTRANS", "NObeyesdad"]

for col in columns:
    df[col] = df[col].astype('category')

In [10]:
#function to integrate data after conversion
#provide min maxx and unique counts

def variable_counts(columns, stage):
    
    if stage == 'pre':
        print("Pre conversion to Integer")
    else:
        print("Post conversion to Integer")
        
    for col in columns:
        print("Variable:", col, "| Count Unique:",df[col].nunique(), "| Min: ", df[col].min(),"| Max: ", df[col].max())

In [11]:
#convert float variables to integer to the nearest int

columns = ["FCVC", "NCP", "CH2O", "TUE", "FAF"]

#pre conversion counts
variable_counts(columns, 'pre')

#convert int to its nearest
for col in columns:
    df[col] = round(df[col]).astype('int')
    
#post converssion counts
print(" ")
variable_counts(columns, 'post')

Pre conversion to Integer
Variable: FCVC | Count Unique: 810 | Min:  1.0 | Max:  3.0
Variable: NCP | Count Unique: 635 | Min:  1.0 | Max:  4.0
Variable: CH2O | Count Unique: 1268 | Min:  1.0 | Max:  3.0
Variable: TUE | Count Unique: 1129 | Min:  0.0 | Max:  2.0
Variable: FAF | Count Unique: 1190 | Min:  0.0 | Max:  3.0

Post conversion to Integer
Variable: FCVC | Count Unique: 3 | Min:  1 | Max:  3
Variable: NCP | Count Unique: 4 | Min:  1 | Max:  4
Variable: CH2O | Count Unique: 3 | Min:  1 | Max:  3
Variable: TUE | Count Unique: 3 | Min:  0 | Max:  2
Variable: FAF | Count Unique: 4 | Min:  0 | Max:  3

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   category
 1   Age                             2111 non-null   float64
 2   family_history_with_overweight  2111 non-null   category
 3   FAVC                            2111 non-null   category
 4   FCVC                            2111 non-null   int64
 5   NCP                             2111 non-null   int64
 6   CAEC                            2111 non-null   category
 7   SMOKE                           2111 non-null   category
 8   CH2O                            2111 non-null   int64
 9   SCC                             2111 non-null   category
 10  FAF                             2111 non-null   int64
 11  TUE                             2111 non-null   int64
 12  CALC                            2111 non-null   category
 13  MTRANS                          2111 non-null   category
 14  NObeyesdad                      2111 non-null   category
dtypes: category(9), float64(1), int64(5)
memory usage: 119.2 KB

In [13]:
df.head()

   Gender   Age  ...                 MTRANS           NObeyesdad
0  Female  21.0  ...  Public_Transportation        Normal_Weight
1  Female  21.0  ...  Public_Transportation        Normal_Weight
2    Male  23.0  ...  Public_Transportation        Normal_Weight
3    Male  27.0  ...                Walking   Overweight_Level_I
4    Male  22.0  ...  Public_Transportation  Overweight_Level_II

[5 rows x 15 columns]

In [14]:
df_prep = df.copy()

In [15]:
df_prep = pd.get_dummies(df_prep, columns = ["Gender", "family_history_with_overweight", "FAVC", "CAEC", "SMOKE", "SCC", "CALC", "MTRANS"])
df_prep.head()

    Age  FCVC  ...  MTRANS_Public_Transportation  MTRANS_Walking
0  21.0     2  ...                             1               0
1  21.0     3  ...                             1               0
2  23.0     2  ...                             1               0
3  27.0     3  ...                             0               1
4  22.0     2  ...                             1               0

[5 rows x 30 columns]

In [16]:
# split dataset in features and target variable

# Features
X = df_prep.drop(columns=["NObeyesdad"])

# Target variable
y = df_prep['NObeyesdad']

In [17]:
# import sklearn packages for data treatments
from sklearn.model_selection import train_test_split # Import train_test_split function

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test

In [18]:
X_train.shape

(1477, 29)

In [19]:
y_train.shape

(1477,)

In [20]:
X_test.shape

(634, 29)

In [21]:
y_test.shape

(634,)

In [22]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.preprocessing import StandardScaler # Import for standard scaling of the data
from sklearn.preprocessing import MinMaxScaler # Import for standard scaling of the data
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error as mae
from sklearn.preprocessing import LabelEncoder


from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

# standard scale data
ss = StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

# tested MinMaxScaler as KNN historically does better with MinMax
mm = MinMaxScaler()
X_train_mm_scaled = ss.fit_transform(X_train)
X_test_mm_scaled = ss.transform(X_test)

# program to run multilple models though sklearn 
# Default settings output accuracy and classification report
# compares accuracy for scaled and unscaled data
def run_models(X_train: pd.DataFrame , y_train: pd.DataFrame, X_test: pd.DataFrame, y_test: pd.DataFrame):
    
    models = [          
          ('Random Forest', RandomForestClassifier(random_state=2020)),
          ('Decision Tree', DecisionTreeClassifier()),                                                 
          ('LR', LogisticRegression()),
          ('SVM', SVC())
        ]  
    
    for name, model in models:        
        # unscaled data
        clf = model.fit(X_train, y_train)
        y_pred = clf.predict(X_test)
        
        # scaled data
        clf_scaled = model.fit(X_train_scaled, y_train)
        y_pred_scaled = clf_scaled.predict(X_test_scaled)
        
        # mm scaled data
        clf_mm_scaled = model.fit(X_train_mm_scaled, y_train)
        y_pred_mm_scaled = clf_scaled.predict(X_test_mm_scaled)
        
        # accuracy scores
        accuracy = round(metrics.accuracy_score(y_test, y_pred),5)
        scaled_accuracy = round(metrics.accuracy_score(y_test, y_pred_scaled),5)
        scaled_mm_accuracy = round(metrics.accuracy_score(y_test, y_pred_mm_scaled),5)
        
        # output
    
        print(name + ':')        
        print("---------------------------------------------------------------")      
        print("Accuracy:", accuracy)
        print("Accuracy w/Scaled Data (ss):", scaled_accuracy)
        print("Accuracy w/Scaled Data (mm):", scaled_mm_accuracy)
        if (accuracy > scaled_accuracy) and (accuracy > scaled_mm_accuracy):
            print("\nClassification Report:\n", metrics.classification_report(y_test, y_pred))      
            print("                            -----------------------------------               \n")      
        elif (scaled_accuracy > scaled_mm_accuracy):
            print("\nClassification Report (ss):\n", metrics.classification_report(y_test, y_pred_scaled))      
            print("                            -----------------------------------               \n")     
        else:            
            print("\nClassification Report (mm):\n", metrics.classification_report(y_test, y_pred_mm_scaled))      
            print("                            -----------------------------------               \n")

In [23]:
#run Decision Trees, Random Forest, KNN and SVM
run_models(X_train, y_train, X_test, y_test)

Random Forest:
---------------------------------------------------------------
Accuracy: 0.82177
Accuracy w/Scaled Data (ss): 0.82177
Accuracy w/Scaled Data (mm): 0.82177

Classification Report (mm):
                      precision    recall  f1-score   support

Insufficient_Weight       0.85      0.87      0.86        92
      Normal_Weight       0.60      0.69      0.64        77
     Obesity_Type_I       0.85      0.80      0.82       114
    Obesity_Type_II       0.90      0.94      0.92        85
   Obesity_Type_III       0.99      0.99      0.99        92
 Overweight_Level_I       0.79      0.71      0.75        89
Overweight_Level_II       0.76      0.74      0.75        85

           accuracy                           0.82       634
          macro avg       0.82      0.82      0.82       634
       weighted avg       0.83      0.82      0.82       634

                            -----------------------------------

Decision Tree:
---------------------------------------------------------------
Accuracy: 0.76025
Accuracy w/Scaled Data (ss): 0.76025
Accuracy w/Scaled Data (mm): 0.75079

Classification Report (ss):
                      precision    recall  f1-score   support

Insufficient_Weight       0.79      0.83      0.81        92
      Normal_Weight       0.54      0.48      0.51        77
     Obesity_Type_I       0.78      0.74      0.76       114
    Obesity_Type_II       0.86      0.87      0.87        85
   Obesity_Type_III       0.98      0.99      0.98        92
 Overweight_Level_I       0.76      0.66      0.71        89
Overweight_Level_II       0.58      0.72      0.64        85

           accuracy                           0.76       634
          macro avg       0.76      0.75      0.75       634
       weighted avg       0.76      0.76      0.76       634

                            -----------------------------------

LR:
---------------------------------------------------------------
Accuracy: 0.57729
Accuracy w/Scaled Data (ss): 0.61356
Accuracy w/Scaled Data (mm): 0.61356

Classification Report (mm):
                      precision    recall  f1-score   support

Insufficient_Weight       0.64      0.73      0.68        92
      Normal_Weight       0.49      0.40      0.44        77
     Obesity_Type_I       0.53      0.60      0.56       114
    Obesity_Type_II       0.56      0.87      0.68        85
   Obesity_Type_III       0.96      0.99      0.97        92
 Overweight_Level_I       0.58      0.44      0.50        89
Overweight_Level_II       0.44      0.22      0.30        85

           accuracy                           0.61       634
          macro avg       0.60      0.61      0.59       634
       weighted avg       0.60      0.61      0.60       634

                            -----------------------------------

SVM:
---------------------------------------------------------------
Accuracy: 0.47319
Accuracy w/Scaled Data (ss): 0.71609
Accuracy w/Scaled Data (mm): 0.71609

Classification Report (mm):
                      precision    recall  f1-score   support

Insufficient_Weight       0.79      0.80      0.80        92
      Normal_Weight       0.54      0.66      0.60        77
     Obesity_Type_I       0.65      0.58      0.61       114
    Obesity_Type_II       0.70      0.98      0.82        85
   Obesity_Type_III       0.98      0.98      0.98        92
 Overweight_Level_I       0.64      0.49      0.56        89
Overweight_Level_II       0.70      0.54      0.61        85

           accuracy                           0.72       634
          macro avg       0.71      0.72      0.71       634
       weighted avg       0.72      0.72      0.71       634

                            -----------------------------------

In [24]:
# Decision Tree

#initialize model
dtc_up = DecisionTreeClassifier()

# fit model
dtc_up.fit(X_train, y_train)

normalized_df_dtc_pred = dtc_up.predict(X_test)

# check accuracy: Accuracy: Overall, how often is the classifier correct? Accuracy = (True Pos + True Negative)/total
acc = accuracy_score(y_test, normalized_df_dtc_pred)
print(f"The accuracy score for DTC is: {round(acc,3)*100}%")

# f1 score: The F1 score can be interpreted as a weighted average of the precision and recall, where an F1 score reaches its best value at 1 and worst score at 0.
f1 = f1_score(y_test, normalized_df_dtc_pred, pos_label='positive', average='micro')
print(f"The f1 score for DTC is: {round(f1,3)*100}%")

# Precision score: When it predicts yes, how often is it correct? Precision=True Positive/predicted yes
precision = precision_score(y_test, normalized_df_dtc_pred, pos_label='positive', average='micro')
print(f"The precision score for DTC is: {round(precision,3)*100}%")

# recall score: True Positive Rate(Sensitivity or Recall): When it’s actually yes, how often does it predict yes? True Positive Rate = True Positive/actual yes
recall = recall_score(y_test, normalized_df_dtc_pred,pos_label='positive', average='micro')
print(f"The recall score for DTC is: {round(recall,3)*100}%")

The accuracy score for DTC is: 76.8%
The f1 score for DTC is: 76.8%
The precision score for DTC is: 76.8%
The recall score for DTC is: 76.8%

In [25]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=20).fit(X_train,y_train)

In [26]:
normalized_rf_pred = rf.predict(X_test)

In [27]:
# check accuracy: Accuracy: Overall, how often is the classifier correct? Accuracy = (True Pos + True Negative)/total
acc = accuracy_score(y_test, normalized_rf_pred)
print(f"The accuracy score for RFC is: {round(acc,3)*100}%")

# f1 score: The F1 score can be interpreted as a weighted average of the precision and recall, where an F1 score reaches its best value at 1 and worst score at 0.
f1 = f1_score(y_test, normalized_rf_pred, pos_label='positive', average='micro')
print(f"The f1 score for RFC is: {round(f1,3)*100}%")

# Precision score: When it predicts yes, how often is it correct? Precision=True Positive/predicted yes
precision = precision_score(y_test, normalized_rf_pred, pos_label='positive', average='micro')
print(f"The precision score for RFC is: {round(precision,3)*100}%")

# recall score: True Positive Rate(Sensitivity or Recall): When it’s actually yes, how often does it predict yes? True Positive Rate = True Positive/actual yes
recall = recall_score(y_test, normalized_rf_pred, pos_label='positive', average='micro')
print(f"The recall score for RFC is: {round(recall,3)*100}%")

The accuracy score for RFC is: 80.9%
The f1 score for RFC is: 80.9%
The precision score for RFC is: 80.9%
The recall score for RFC is: 80.9%

In [29]:
# logistic regression again with the balanced dataset

normalized_df_reg = LogisticRegression().fit(X_train, y_train)

normalized_df_reg_pred = normalized_df_reg.predict(X_test)

# check accuracy: Accuracy: Overall, how often is the classifier correct? Accuracy = (True Pos + True Negative)/total
acc = accuracy_score(y_test, normalized_df_reg_pred)
print(f"The accuracy score for LogReg is: {round(acc,3)*100}%")

# f1 score: The F1 score can be interpreted as a weighted average of the precision and recall, where an F1 score reaches its best value at 1 and worst score at 0.
f1 = f1_score(y_test, normalized_df_reg_pred, pos_label='positive', average='micro')
print(f"The f1 score for LogReg is: {round(f1,3)*100}%")

# Precision score: When it predicts yes, how often is it correct? Precision=True Positive/predicted yes
precision = precision_score(y_test, normalized_df_reg_pred, pos_label='positive', average='micro')
print(f"The precision score for LogReg is: {round(precision,3)*100}%")

# recall score: True Positive Rate(Sensitivity or Recall): When it’s actually yes, how often does it predict yes? True Positive Rate = True Positive/actual yes
recall = recall_score(y_test, normalized_df_reg_pred, pos_label='positive', average='micro')
print(f"The recall score for LogReg is: {round(recall,3)*100}%")

# As they were categorical data, it can be encoded to get the mean absolute error as MAE only works on int or float values.
encoder = LabelEncoder()

#encoding Y test values 
y_test = encoder.fit_transform(y_test)

#As normalized_df_reg_pred is in object type, it should be converted to data frame to apply label encoding 
normalized_df_reg_pred = pd.DataFrame(normalized_df_reg_pred)

#applying label encoding
normalized_df_reg_pred = encoder.fit_transform(normalized_df_reg_pred)
print(f'Mean Absolute Error: {mae(y_test, normalized_df_reg_pred)}')

The accuracy score for LogReg is: 57.699999999999996%
The f1 score for LogReg is: 57.699999999999996%
The precision score for LogReg is: 57.699999999999996%
The recall score for LogReg is: 57.699999999999996%
Mean Absolute Error: 1.0678233438485805

In [ ]:
(from google.colab import drive
drive.mount('/content/drive')